config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions",
  }


  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
  }
  


  scope module: :public do
    root to: "homes#top"
    get "homes/about"
    get 'cart_items/index'
    get "customers/information/edit" => "customers#edit", as: "customers_edit"
    get "customers/mypage" => "customers#show", as: "customers_mypage"
    patch "customers/update" => "customers#update"
    get "customers/confirm" => "customers#confirm", as: "customer_confirm"
    patch "customers/cancel" => "customers#cancel", as: "customer_cancel"
    delete "cart_items/destroy_all" => "cart_items#destroy_all"

     resources :cart_items, only: [:index, :update, :destroy, :create] do
     member do
       patch 'increase'
       patch 'decrease'
     end
   end

    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:index, :show, :new, :create]
    post "orders/confirm" => "orders#confirm"


   resources :items, only: [:index, :show]

  end


  namespace :admin do
    get 'post_images/index'

    get "top" => "homes#top", as: "top"
    get "show" => "homes#show", as: "show"

    resources :items, expect: [:destroy]
resources :orders
    resources :customers, expect: [:new, :destroy, :create]
  end
  #get "orders/:id/show" => "/orders/:id#show", as: "orders_show"


    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
has_many :order_details  
  

def get_item_image(hight, width)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [hight, width]).processed
end

def with_tax_price
    (price * 1.1).floor
end

def add_tax_sales_price
  (self.price * 1.10).round
end

private

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
layout 'admin'

  def new
    @item = Item.new
  end


def create
    @item = Item.new(item_params)
  if @item.save
    redirect_to admin_item_path(@item.id)
  else
    render :new
  end
end

def index
   @items = Item.all

end

def show
  @item = Item.find(params[:id])
  
end

def edit
      @item = Item.find(params[:id])

end

def update
  @item = Item.find(params[:id])
  if @item.update(item_params)
    flash[:notice] = "You have updated user successfully."
      redirect_to  admin_items_path
  else
      render :edit
  end
end

  private

def item_params
    params.require(:item).permit(:name, :image, :introduction, :price)
end




end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/create.html.erb
<h1>管理者トップページ</h1>

app/views/admin/items/edit.html.erb
<h2>商品編集</h2>
<%= form_with model: @item,url: admin_item_path do |f| %>
<label for="inputImage">ProfileImage</label>
  <%= f.file_field :item_image, placeholder: "商品画像", accept: "image/*" %>

  <label for="inputName">商品名</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name"%>

  <label for="Introduction">商品詳細</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction"%>


<label for="Price">税抜価格</label>
  <%= f.text_field :price, autofocus: true, id:"inputprice", placeholder:"Price"%>



  <%= f.submit "変更を保存" %>

<% end %>

app/views/admin/items/index.html.erb
<html>
<h1>商品一覧</h1>

<p><%= link_to "新規登録", new_admin_item_path %></p>

<table>  
  <tr>
    <th>商品ID</th>
    <th>商品名</th>
    <th>税抜価格</th>
  </tr>  

<% @items.each do |item| %>
<tr>
  <td><%= item.id %></td>
  <td><%= link_to admin_item_path(item.id) do %>
  <%= item.name %>
  <% end %></td>
  <td><%= item.price %></td>
<% end %>
</tr>
</table>
</html>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>
  <%= form_with model: @item,url: admin_items_path, method: :POST do |f| %>
    <h4>商品画像</h4>
      <%= f.file_field :image, accept: "image/*" %>
    <h4>商品名</h4>
      <%= f.text_field :name %>
    <h4>商品説明</h4>
      <%= f.text_area :introduction %>
      <h4>税抜価格</h4>
      <%= f.text_area :price %>
    <%= f.submit '新規登録' %>
  <% end %>

app/views/admin/items/show.html.erb
<p>商品詳細</p>


<div>

  <p><%= image_tag @item.get_item_image(100, 100) %></p>
  <p>商品名：<%= @item.name %></p>
  <p>商品説明：<%= @item.introduction %></p>
 <p>税込価格(税抜価格): <%= @item.add_tax_sales_price.to_s(:dalimited) %>
  (<%= @item.price %>)円</p>
<p><%= link_to "商品編集", edit_admin_item_path %></p>
</div>