config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions",
  }


  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
  }
  


  scope module: :public do
    root to: "homes#top"
    get "homes/about"
    get 'cart_items/index'
    get "customers/information/edit" => "customers#edit", as: "customers_edit"
    get "customers/mypage" => "customers#show", as: "customers_mypage"
    patch "customers/update" => "customers#update"
    get "customers/confirm" => "customers#confirm", as: "customer_confirm"
    patch "customers/cancel" => "customers#cancel", as: "customer_cancel"
    delete "cart_items/destroy_all" => "cart_items#destroy_all"

     resources :cart_items, only: [:index, :update, :destroy, :create] do
     member do
       patch 'increase'
       patch 'decrease'
     end
   end

    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:index, :show, :new, :create]
    post "orders/confirm" => "orders#confirm"


   resources :items, only: [:index, :show]

  end


  namespace :admin do
    get 'post_images/index'

    get "top" => "homes#top", as: "top"
    get "show" => "homes#show", as: "show"

    resources :items, expect: [:destroy]
resources :orders
    resources :customers, expect: [:new, :destroy, :create]
  end
  #get "orders/:id/show" => "/orders/:id#show", as: "orders_show"


    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 # def active_for_authentication?
    #super && (is_deleted == true)
    has_many :cart_items, dependent: :destroy
    has_many :orders
  #end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  layout 'admin'
def index
   @customers = Customer.all

end

def edit
  @customer = Customer.find(params[:id])
end

def show
  @customer = Customer.find(params[:id])

end

def update
  @customer = Customer.find(params[:id])
      if @customer.update(customer_params)
        flash[:notice] = "You have updated user successfully."
          redirect_to admin_customers_path
      else
          render :edit
      end
end

private

  def customer_params
  params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number)
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<p><%= @customer.last_name + " " + @customer.first_name %>の会員情報編集</p>
<%= form_with model: @customer,url: admin_customer_path(@customer.id), method: :PATCH do |f| %>
 
  <label for="inputLast_name">氏名</label>
  <%= f.text_field :Last_name, autofocus: true, id:"inputLast_name", placeholder:"Last_name"%>

  <label for="inputFirst_name"></label>
  <%= f.text_field :First_name, autofocus: true, id:"inputFirst_name", placeholder:"First_name"%><br>

  <label for="inputLast_name_kana">フリガナ</label>
  <%= f.text_field :Last_name_kana, autofocus: true, id:"inputLast_name_kana", placeholder:"Last_name_kana"%>

  <label for="inputFirst_name_kana"></label>
  <%= f.text_field :First_name_kana, autofocus: true, id:"inputFirst_name_kana", placeholder:"First_name_kana"%><br>


  <label for="inputPostal_code">郵便番号</label>
  <%= f.text_field :Postal_code, autofocus: true, id:"inputPostal_code", placeholder:"Postal_code"%><br>

  <label for="inputAddress">住所</label>
  <%= f.text_field :Address, autofocus: true, id:"inputAddress", placeholder:"Address"%><br>

  <label for="inputTelephone_number">電話番号</label>
  <%= f.text_field :Telephone_number, autofocus: true, id:"inputTelephone_number", placeholder:"Telephone_number"%><br>

    <label for="inputEmail">メールアドレス</label>
    
  <%= f.text_field :Email, autofocus: true, id:"inputEmail", placeholder:"Email"%><br>


  <%= f.submit "変更を保存" %>

<% end %>

app/views/admin/customers/index.html.erb
<h1>会員一覧</h1>

<% @customers.each do |customer| %>

<div>
<p>氏名</p>
 <%= link_to admin_customer_path(customer.id) do %>
 <%= customer.last_name + " " + customer.first_name %>
 <% end %>

<p>メールアドレス</p>
 <%= customer.email %>

<p>ステータス</p>

 <% if customer.is_deleted %>
   <p>無効</p>

 <% else %>
    <p>有効</p>
 <% end %>

</div>

 <% end %>

app/views/admin/customers/show.html.erb
<p><%= @customer.last_name + " " + @customer.first_name %>の会員詳細</p>

<p>氏名</p>
<%= @customer.last_name + " " + @customer.first_name %>


<p>カナ</p>
<%= @customer.last_name_kana + " " + @customer.first_name_kana %>

<p>郵便番号</p>
<%= @customer.postal_code %>


<p>住所</p>
<%= @customer.address %>


<p>電話番号</p>
<%= @customer.telephone_number %>


<p>メールアドレス</p>
<%= @customer.email %>


<%= link_to "編集", edit_admin_customer_path(@customer.id) %>