config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions",
  }


  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
  }
  


  scope module: :public do
    root to: "homes#top"
    get "homes/about"
    get 'cart_items/index'
    get "customers/information/edit" => "customers#edit", as: "customers_edit"
    get "customers/mypage" => "customers#show", as: "customers_mypage"
    patch "customers/update" => "customers#update"
    get "customers/confirm" => "customers#confirm", as: "customer_confirm"
    patch "customers/cancel" => "customers#cancel", as: "customer_cancel"
    delete "cart_items/destroy_all" => "cart_items#destroy_all"

     resources :cart_items, only: [:index, :update, :destroy, :create] do
     member do
       patch 'increase'
       patch 'decrease'
     end
   end

    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:index, :show, :new, :create]
    post "orders/confirm" => "orders#confirm"


   resources :items, only: [:index, :show]

  end


  namespace :admin do
    get 'post_images/index'

    get "top" => "homes#top", as: "top"
    get "show" => "homes#show", as: "show"

    resources :items, expect: [:destroy]
resources :orders
    resources :customers, expect: [:new, :destroy, :create]
  end
  #get "orders/:id/show" => "/orders/:id#show", as: "orders_show"


    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



end

app/models/address.rb
class Address < ApplicationRecord

def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    has_one_attached :image

  belongs_to :customer
  belongs_to :item

def subtotal
    item.with_tax_price * amount
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 # def active_for_authentication?
    #super && (is_deleted == true)
    has_many :cart_items, dependent: :destroy
    has_many :orders
  #end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
has_many :order_details  
  

def get_item_image(hight, width)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [hight, width]).processed
end

def with_tax_price
    (price * 1.1).floor
end

def add_tax_sales_price
  (self.price * 1.10).round
end

private

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  has_many :order_details 
    belongs_to :customer
def with_tax_price
    (price * 1.1).floor
end   
    
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
    belongs_to :item

def subtotal
    item.with_tax_price * amount
end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  layout 'admin'
def index
   @customers = Customer.all

end

def edit
  @customer = Customer.find(params[:id])
end

def show
  @customer = Customer.find(params[:id])

end

def update
  @customer = Customer.find(params[:id])
      if @customer.update(customer_params)
        flash[:notice] = "You have updated user successfully."
          redirect_to admin_customers_path
      else
          render :edit
      end
end

private

  def customer_params
  params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number)
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  layout 'admin'
   before_action :authenticate_admin!

  def top
    @orders = Order.all
  end



end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
layout 'admin'

  def new
    @item = Item.new
  end


def create
    @item = Item.new(item_params)
  if @item.save
    redirect_to admin_item_path(@item.id)
  else
    render :new
  end
end

def index
   @items = Item.all

end

def show
  @item = Item.find(params[:id])
  
end

def edit
      @item = Item.find(params[:id])

end

def update
  @item = Item.find(params[:id])
  if @item.update(item_params)
    flash[:notice] = "You have updated user successfully."
      redirect_to  admin_items_path
  else
      render :edit
  end
end

  private

def item_params
    params.require(:item).permit(:name, :image, :introduction, :price)
end




end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
layout 'admin'
  def show
    @order = Order.find(params[:id])
    @order_d = @order.order_details
    @sum = 0
  end



 private

def order_params
   params.require(:oder).permit(:customer_id, :payment_amount, :shipping_address, :postal_code, :name, :postage, :payment_method,)
end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  layout 'admin'
  def after_sign_in_path_for(resource)
    admin_top_path
  end

  def after_sign_out_path_for(resource)
    admin_session_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
    public_items_path 
end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :is_deleted])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cakes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>
    <% if admin_signed_in? %>
    <li>
    <%= link_to '注文履歴一覧', admin_top_path %>
    </li>
     
    <li>
    <%= link_to '商品一覧', admin_items_path %>
    </li>
    <li>
    <%= link_to '商品新規登録', new_admin_item_path %>
  </li>
      <li>
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
      </li>
      <li>
    <%= link_to '会員一覧', admin_customers_path %>
  </li>
    <% else %>
      <li>
        <%= link_to "ログイン", new_admin_session_path %>
      </li>
    <% end %>
  </header>  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cakes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <% if customer_signed_in? %>
     <li>
      <%= link_to 'マイページ', customers_mypage_path(current_customer.id) %>    </li>

      <li>
        <%= link_to "商品一覧", items_path %>
      </li>
      <li>
      <%= link_to 'カート', cart_items_path(current_customer.id) %>    </li>
        <li>
        <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
      </li>
    <% else %>
    <li>
        <%= link_to "About", homes_about_path %>
      </li>
       <li>
        <%= link_to "商品一覧", root_path %>
      </li>
       <li>
        <%= link_to "新規登録", new_customer_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_customer_session_path %>
      </li>
      
     
       
       
      
    <% end %>
  </header>  <%= yield %>
</body>
</html>